name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the dev environment
      run: make resetup
    - name: Build rom
      run: make
    - name: List rom
      run: ls -lah *.z64
    - name: Cleanup
      run: make clean
